### ISSUE TITLE
private token in two places on repo (Solved)

### ISSUE THREAD

**Issue by danielgraycode** [KadonWills/DivineCodeBot#1]
Hi! Big issue, your bot token was left in twice within the program repo. We think it has also been compromised and used for a malicious campaign. Might want to remove it and change your bot token.
-Daniel

**Comment by KadonWills** [comment]
Yeah thanks, I regenerated it immediately after noticing that.

**Comment by danielgraycode** [comment]
Awesome! Looks like this doesn't need to be open anymore
